config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }
  root to: 'pages#home'
  namespace :admin do
    root to: 'pages#home'
    resources :products, only: %i[index show new create edit update]
    resources :orders, only: %i[show update]
    resources :customers, only: %i[index show update]
  end
  scope module: :customer do
    resources :products, only: %i[index show]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch 'increase'
        patch 'decrease'
      end
    end
    resources :checkouts, only: [:create]
    resources :webhooks, only: [:create]
    resources :orders, only: %i[index show] do
      collection do
        get 'success'
      end
    end
    resources :customers do
      collection do 
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
  end

  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :description
    validates :price
    validates :stock
    validates :image
  end
  has_one_attached :image
  scope :price_high_to_low, -> { order(price: :desc) }
  scope :price_low_to_high, -> { order(price: :asc) }
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :image)
  end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products, @sort = get_products(params)
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  def get_products(params)
    return Product.all, 'default' unless params[:latest] || params[:price_high_to_low] || params[:price_low_to_high]

    return Product.latest, 'latest' if params[:latest]

    return Product.price_high_to_low, 'price_high_to_low' if params[:price_high_to_low]

    return Product.price_low_to_high, 'price_low_to_high' if params[:price_low_to_high]
  end
end

app/views/admin/products/edit.html.erb
<div class="mb-6 text-center">
    <span class="text-3xl font-bold">
      Edit Product
    </span>
  </div>
  
  <div class='flex flex-wrap justify-center'>
    <%= form_with model: @product, url: admin_product_path(@product), local: true, class: "xl:w-8/12 md:w-10/12", data: { turbo: false }  do |f| %>
      <%= render "admin/shared/error_messages", resource: @product %>
      <div class="mb-6">
        <%= f.label :name, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.text_field :name, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
      </div>
      <div class="mb-6">
        <%= f.label :description, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.text_area :description, rows: "5", class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
      </div>
      <div class="mb-6">
        <%= f.label :price, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.number_field :price, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
      </div>
      <div class="mb-6">
        <%= f.label :stock, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.number_field :stock, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
      </div>
      <div class="mb-6">
        <%= f.label :image, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.file_field :image, class: "block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
      </div>
      <%= f.submit class: "inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none" %>
    <% end %>
  </div>

app/views/admin/products/index.html.erb
<div class="mb-8 text-center">
    <span class="text-3xl font-bold">
      Products
    </span>
  </div>
  
  <div class="flex flex-wrap">
    <div class="flex-none w-full max-w-full px-6">
      <%= link_to new_admin_product_path, class: "mb-4 inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none" do %>
        Add New Product
      <% end %>
      <div class="relative flex flex-col min-w-0 mb-6 break-words bg-white border-0 border-transparent border-solid shadow-soft-xl rounded-2xl bg-clip-border">
        <div class="flex-auto px-0 pt-0 pb-2">
          <div class="p-0 overflow-x-auto">
            <table class="items-center w-full mb-0 align-top border-gray-200 text-slate-500">
              <thead class="align-bottom">
                <tr>
                  <th class="px-6 py-3 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Image & Name</th>
                  <th class="px-6 py-3 pl-2 font-bold text-left uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Price</th>
                  <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">Stock</th>
                  <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">CreatedAt</th>
                  <th class="px-6 py-3 font-bold text-center uppercase align-middle bg-transparent border-b border-gray-200 shadow-none text-xxs border-b-solid tracking-none whitespace-nowrap text-slate-400 opacity-70">UpdatedAt</th>
                  <th class="px-6 py-3 font-semibold capitalize align-middle bg-transparent border-b border-gray-200 border-solid shadow-none tracking-none whitespace-nowrap text-slate-400 opacity-70"></th>
                </tr>
              </thead>
              <tbody>
                <% @products.each do |product| %>
                  <tr>
                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <%= link_to admin_product_path(product) do %>
                        <div class="flex px-2 py-1">
                          <div class="w-16 mr-5">
                            <%= image_tag product.image, class: "inline-flex items-center justify-center mr-4 text-white transition-all duration-200 ease-soft-in-out text-sm rounded-xl object-fill" %>
                          </div>
                          <div class="flex flex-col justify-center">
                            <h6 class="text-lg font-bold"><%= product.name %></h6>
                          </div>
                        </div>
                      <% end %>
                    </td>
                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <p class="font-semibold leading-tight text-sm"><%= number_to_currency(product.price, unit: "¥", strip_insignificant_zeros: true) %></p>
                    </td>
                    <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <span class="font-semibold leading-tight text-sm text-slate-400"><%= product.stock %></span>
                    </td>
                    <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <span class="font-semibold leading-tight text-sm text-slate-400"><%= l product.created_at, format: :short %></span>
                    </td>
                    <td class="p-2 text-center align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <span class="font-semibold leading-tight text-sm text-slate-400"><%= l product.updated_at, format: :short %></span>
                    </td>
                    <td class="p-2 align-middle bg-transparent border-b whitespace-nowrap shadow-transparent">
                      <%= link_to edit_admin_product_path(product), class: "font-semibold leading-tight text-xs text-slate-400" do %>
                        Edit
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/products/new.html.erb
<div class="mb-6 text-center">
    <span class="text-3xl font-bold">
        New Product
    </span>
</div>

<div class='flex flex-wrap justify-center'>
    <%= form_with model: @product, url: admin_products_path, local: true, class: "xl:w-8/12 md:w-10/12", data: { turbo: false }  do |f| %>
        <%= render "admin/shared/error_messages", resource: @product %>
        <div class="mb-6">
        <%= f.label :name, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.text_field :name, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
        </div>
        <div class="mb-6">
        <%= f.label :description, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.text_area :description, rows: "5", class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
        </div>
        <div class="mb-6">
        <%= f.label :price, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.number_field :price, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
        </div>
        <div class="mb-6">
        <%= f.label :stock, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.number_field :stock, class: "w-full rounded-md border border-gray-300 py-2 px-3 placeholder:text-gray-300 focus:border-indigo-300 focus:outline-none focus:ring focus:ring-indigo-100" %>
        </div>
        <div class="mb-6">
        <%= f.label :image, class: "mb-2 block text-sm text-gray-600" %>
        <%= f.file_field :image, class: "block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" %>
        </div>
        <%= f.submit class: "inline-flex w-full items-center justify-center rounded-md bg-indigo-500 p-3 text-white duration-100 ease-in-out hover:bg-indigo-600 focus:outline-none cursor-pointer" %>
    <% end %>
</div>

app/views/admin/products/show.html.erb
<div class="relative mx-auto max-w-screen-xl p-6">
    <div class="grid grid-cols-1 items-start gap-9 md:grid-cols-2">
      <div>
        <%= image_tag @product.image, class: "aspect-square w-full rounded-xl object-cover" %>
      </div>
  
      <div class="sticky top-0">
        <div class="flex flex-col justify-between">
          <div class="flex justify-between mb-6">
            <div class="max-w-[35ch]">
              <h1 class="text-2xl font-bold">
                <%= @product.name %>
              </h1>
            </div>
            <p class="text-2xl font-bold"><%= number_to_currency(@product.price, unit: "¥", strip_insignificant_zeros: true) %></p>
          </div>
  
          <div class="mb-8">
            <p>
              <%= @product.description %>
            </p>
          </div>
  
          <div class="flex">
            <div>
              <% if @product.stock > 0 %>
                <span class="bg-blue-100 text-blue-800 text-sm font-semibold p-2.5 rounded">In stock (<%= @product.stock %>)</span>
              <% else %>
                <span class="bg-red-100 text-red-800 text-sm font-semibold p-2.5 rounded">Out of stock</span>
              <% end %>
            </div>
            <div class="ml-4">
            <%= link_to edit_admin_product_path(@product), class: "text-center cursor-pointer focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2" do %>
              Edit Product
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>