config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions'
  }
  devise_for :customers, controllers: {
    sessions: 'customer/sessions',
    registrations: 'customer/registrations'
  }
  root to: 'pages#home'
  namespace :admin do
    root to: 'pages#home'
    resources :products, only: %i[index show new create edit update]
    resources :orders, only: %i[show update]
    resources :customers, only: %i[index show update]
  end
  scope module: :customer do
    resources :products, only: %i[index show]
    resources :cart_items, only: %i[index create destroy] do
      member do
        patch 'increase'
        patch 'decrease'
      end
    end
    resources :checkouts, only: [:create]
    resources :webhooks, only: [:create]
    resources :orders, only: %i[index show] do
      collection do
        get 'success'
      end
    end
    resources :customers do
      collection do 
        get 'confirm_withdraw'
        patch 'withdraw'
      end
    end
  end

  get '/up/', to: 'up#index', as: :up
  get '/up/databases', to: 'up#databases', as: :up_databases

  # Sidekiq has a web dashboard which you can enable below. It's turned off by
  # default because you very likely wouldn't want this to be available to
  # everyone in production.
  #
  # Uncomment the 2 lines below to enable the dashboard WITHOUT authentication,
  # but be careful because even anonymous web visitors will be able to see it!
  # require "sidekiq/web"
  # mount Sidekiq::Web => "/sidekiq"
  #
  # If you add Devise to this project and happen to have an admin? attribute
  # on your user you can uncomment the 4 lines below to only allow access to
  # the dashboard if you're an admin. Feel free to adjust things as needed.
  # require "sidekiq/web"
  # authenticate :user, lambda { |u| u.admin? } do
  #   mount Sidekiq::Web => "/sidekiq"
  # end

  # Learn more about this file at: https://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  def line_total
    product.price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name
    validates :status
  end
  enum status: {
    normal: 0,
    withdrawn: 1,
    banned: 2
  }
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def line_items_checkout
    cart_items.map do |cart_item|
      {
        quantity: cart_item.quantity,
        price_data: {
          currency: 'jpy',
          unit_amount: cart_item.product.price,
          product_data: {
            name: cart_item.product.name,
            metadata: {
              product_id: cart_item.product_id
            }
          }
        }
      }
    end
  end

  def active_for_authentication?
    super && (status == 'normal')
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_customer, only: %i[show update]

  def index
    @customers = Customer.preload(:orders).latest
  end

  def show; end

  def update
    @customer.update(customer_params)
    redirect_to request.referer, notice: 'Successfully updated customer status'
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:status)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_cart_item, only: %i[increase decrease destroy]

  def index
    @cart_items = current_customer.cart_items
    @total=@cart_items.inject(0){ |sum, cart_item| sum + cart_item.line_total}
  end

  def create
    increase_or_create(params[:cart_item][:product_id])
    redirect_to cart_items_path, notice: 'Successfully added product to your cart'
  end

  def increase
    @cart_item.increment!(:quantity, 1)
    redirect_to request.referer, notice: 'Successfully updated your cart'
  end

  def decrease
    decrease_or_destroy(@cart_item)
    redirect_to request.referer, notice: 'Successfully updated your cart'
  end

  def destroy
    @cart_item.destroy
    redirect_to request.referer, notice: 'Successfully deleted one cart item'
  end

  private

  def set_cart_item
    @cart_item = current_customer.cart_items.find(params[:id])
  end

  def increase_or_create(product_id)
    cart_item = current_customer.cart_items.find_by(product_id:)
    if cart_item
      cart_item.increment!(:quantity, 1)
    else
      current_customer.cart_items.build(product_id:).save
    end
  end

  def decrease_or_destroy(cart_item)
    if cart_item.quantity > 1
      cart_item.decrement!(:quantity, 1)
    else
      cart_item.destroy
    end
  end
end

app/controllers/customer/checkouts_controller.rb
class Customer::CheckoutsController < ApplicationController
    before_action :authenticate_customer!
  
    def create
      line_items = current_customer.line_items_checkout
      session = create_session(line_items)
      # Allow redirection to the host that is different to the current host
      redirect_to session.url, allow_other_host: true
    end
  
    private
  
    def create_session(line_items)
      Stripe::Checkout::Session.create(
        client_reference_id: current_customer.id,
        customer_email: current_customer.email,
        mode: 'payment',
        payment_method_types: ['card'],
        line_items:,
        shipping_address_collection: {
          allowed_countries: ['JP']
        },
        shipping_options: [
          {
            shipping_rate_data: {
              type: 'fixed_amount',
              fixed_amount: {
                amount: 500,
                currency: 'jpy'
              },
              display_name: '全国一律'
            }
          }
        ],
        success_url: "#{root_url}orders/success",
        cancel_url: "#{root_url}cart_items"
      )
    end
  end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!

  def confirm_withdraw; end

  def withdraw
    current_customer.update(status: 'withdrawn')
    reset_session
    redirect_to root_path, notice: 'Successfully withdraw from Ecommerce'
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
    @orders = current_customer.orders.latest
  end

  def show
    @order = current_customer.orders.find(params[:id])
  end

  def success; end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/products_controller.rb
class Customer::ProductsController < ApplicationController
  def index
    @products, @sort = get_products(params)
  end

  def show
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  private

  def get_products(params)
    return Product.all, 'default' unless params[:latest] || params[:price_high_to_low] || params[:price_low_to_high]

    return Product.latest, 'latest' if params[:latest]

    return Product.price_high_to_low, 'price_high_to_low' if params[:price_high_to_low]

    return Product.price_low_to_high, 'price_low_to_high' if params[:price_low_to_high]
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_invalid_customer, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_invalid_customer
    customer = Customer.find_by(email: params[:customer][:email])
    return unless customer

    return if customer.valid_password?(params[:customer][:password]) && customer.active_for_authentication?

    alert_message = if customer.status == 'withdrawn'
      'You have already resigned'
    else
      'Your account is suspended'
    end
    redirect_to request.referer, alert: alert_message
  end
end

app/controllers/customer/unlocks_controller.rb
# frozen_string_literal: true

class Customer::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/webhooks_controller.rb
class Customer::WebhooksController < ApplicationController
    skip_before_action :verify_authenticity_token
  
    def create
      payload = request.body.read
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      endpoint_secret = Rails.application.credentials.dig(:stripe, :endpoint_secret)
      event = nil
  
      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, endpoint_secret
        )
      rescue JSON::ParserError => e
        # Invalid payload
        p e
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        p e
        status 400
        return
      end
  
      case event.type
      when 'checkout.session.completed'
        session = event.data.object # sessionの取得
        customer = Customer.find(session.client_reference_id)
        return unless customer # 顧客が存在するかどうか確認
        
        # トランザクション処理開始
        ApplicationRecord.transaction do
          order = create_order(session) # sessionを元にordersテーブルにデータを挿入
          session_with_expand = Stripe::Checkout::Session.retrieve({ id: session.id, expand: ['line_items'] })
          session_with_expand.line_items.data.each do |line_item|
            create_order_details(order, line_item)
          end
        end
        # トランザクション処理終了
        customer.cart_items.destroy_all
        redirect_to session.success_url
      end
    end
    
    private

    def create_order(session)
        Order.create!({
            customer_id: session.client_reference_id,
            name: session.shipping.name,
            postal_code: session.shipping.address.postal_code,
            prefecture: session.shipping.address.state,
            address1: session.shipping.address.line1,
            address2: session.shipping.address.line2,
            postage: session.shipping_options[0].shipping_amount,
            billing_amount: session.amount_total,
            status: 'confirm_payment'
        })
    end

    def create_order_details(order, line_item)
        product = Stripe::Product.retrieve(line_item.price.product)
        purchased_product = Product.find(product.metadata.product_id)
        raise ActiveRecord::RecordNotFound if purchased_product.nil?

        order_detail = order.order_details.create!({
            product_id: purchased_product.id,
            price: line_item.price.unit_amount,
            quantity: line_item.quantity
        })
        purchased_product.update!(stock: (purchased_product.stock - order_detail.quantity)) # 購入された商品の在庫数の更新
    end
  end

app/helpers/customer/cart_items_helper.rb
module Customer::CartItemsHelper
    def total_quantity(cart_items)
        cart_items.sum(:quantity)
    end
end

app/views/customer/cart_items/index.html.erb
<div class="mb-8 text-center">
    <span class="text-3xl font-bold">
      Shopping Cart
    </span>
  </div>
  
  <% if @cart_items.count == 0 %>
    <div class='mx-auto max-w-3xl'>
      <p class='mb-8 text-xl text-center'>No item</p>
      <div class='flex justify-center'>
        <%= link_to products_path, class: 'group inline-flex items-center justify-center overflow-hidden rounded-lg bg-gradient-to-br from-purple-600 to-blue-500 p-0.5 font-medium text-gray-900 hover:text-white focus:ring-4 focus:ring-blue-300 group-hover:from-purple-600 group-hover:to-blue-500' do %>
          <span class='rounded-md bg-white px-5 py-2.5 transition-all duration-75 ease-in group-hover:bg-opacity-0'>
            Find Products
          </span>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="xl:flex">
      <div class="px-6 flex justify-center mb-7 xl:w-2/3">
        <div class="overflow-x-auto">
          <table>
            <thead>
              <tr class="bg-gray-100 text-gray-600 uppercase text-sm leading-normal">
                <th class="py-4 px-8">product</th>
                <th class="py-4 px-8">price</th>
                <th class="py-4 px-8">quantity</th>
                <th class="py-4 px-8">total</th>
                <th class="py-4 px-8"></th>
              </tr>
            </thead>
            <tbody class="text-center">
              <% @cart_items.each do |cart_item| %>
                <tr class="focus:outline-none h-16 border border-gray-100 rounded">
                  <td class="p-3 whitespace-nowrap">
                    <div class="flex flex-col justify-center mx-6">
                      <span class="font-bold text-xl"><%= cart_item.product.name %></span>
                      <span class="text-sm"><%= cart_item.product.stock %> left in stock</span>
                    </div>
                  </td>
                  <td class="p-3">
                    <span class="text-lg"><%= number_to_currency(cart_item.product.price, unit: "¥", strip_insignificant_zeros: true) %></span>
                  </td>
                  <td class="p-3">
                    <div class="flex justify-center">
                      <%= link_to decrease_cart_item_path(cart_item), data: { "turbo-method": :patch }, class: "flex justify-center" do %>
                        <svg class="fill-current text-red-500 w-3" viewBox="0 0 448 512">
                          <path d="M416 208H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h384c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
                        </svg>
                      <% end %>
                      <span class="mx-5 text-lg"><%= cart_item.quantity %></span>
                      <% unless cart_item.quantity >= cart_item.product.stock %>
                        <%= link_to increase_cart_item_path(cart_item), data: { "turbo-method": :patch }, class: "flex justify-center" do %>
                          <svg class="fill-current text-blue-500 w-3" viewBox="0 0 448 512">
                            <path d="M416 208H272V64c0-17.67-14.33-32-32-32h-32c-17.67 0-32 14.33-32 32v144H32c-17.67 0-32 14.33-32 32v32c0 17.67 14.33 32 32 32h144v144c0 17.67 14.33 32 32 32h32c17.67 0 32-14.33 32-32V304h144c17.67 0 32-14.33 32-32v-32c0-17.67-14.33-32-32-32z"/>
                          </svg>
                        <% end %>
                      <% end %>
                    </div>
                  </td>
                  <td class="p-3">
                    <span class="text-lg"><%= number_to_currency(cart_item.line_total, unit: "¥", strip_insignificant_zeros: true)%></span>
                  </td>
                  <td class="p-3">
                    <div class="flex justify-center">
                      <%= link_to cart_item_path(cart_item), data: { "turbo-method": :delete, "turbo_confirm": 'Are you sure?' } do %>
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash text-red-500" viewBox="0 0 16 16">
                          <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                          <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                        </svg>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="px-6 xl:w-1/3">
        <h1 class="font-semibold text-2xl border-b pb-6 text-center">
          Cart Summary
        </h1>
        <div class="flex justify-between my-6">
          <span class="font-semibold text-lg uppercase">subtotal</span>
          <span class="font-semibold text-lg"><%= number_to_currency(@total,unit:'Y',strip_insignificant_zeros: true)%></span>
        </div>
        <div class="flex justify-between my-6">
          <span class="font-semibold text-lg uppercase">postage</span>
          <span class="font-semibold text-lg"><%= number_to_currency(POSTAGE,unit:'Y',strip_insignificant_zeros: true)%></span>
        </div>
        <div class="flex justify-between my-6">
          <span class="font-semibold text-lg uppercase">total</span>
          <span class="font-semibold text-lg"><%= number_to_currency(@total + POSTAGE,unit:'Y',strip_insignificant_zeros: true)%></span>
        </div>
        <%= button_to checkouts_path, data: { turbo: false }, class:'w-full cursor-pointer focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2' do %>
          Checkout
        <% end %>
      </div>
    </div>
  <% end %>